FROM node:14

# Create app directory
WORKDIR /app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . .

ENV REACT_APP_SERVER_URL_ORIGIN=http://localhost:8080

EXPOSE 3000
CMD [ "npm", "start" ]
